// Mock data for stays and hosts

export const getFeaturedDestinations = () => [
  {
    id: 1,
    name: 'Bwindi Impenetrable National Park',
    slug: 'bwindi',
    description: 'Experience the majesty of mountain gorillas in their natural habitat',
    image: 'https://images.unsplash.com/photo-1551033406-611cf9a28f67?w=800&q=80',
    stays: 42,
    priceRange: '80,000 - 500,000',
    rating: 4.8,
  },
  {
    id: 2,
    name: 'Queen Elizabeth National Park',
    slug: 'queen-elizabeth',
    description: 'Witness the famous tree-climbing lions and diverse wildlife',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80',
    stays: 38,
    priceRange: '60,000 - 400,000',
    rating: 4.7,
  },
  {
    id: 3,
    name: 'Murchison Falls National Park',
    slug: 'murchison',
    description: 'See the Nile River explosively force through a narrow gorge',
    image: 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=800&q=80',
    stays: 35,
    priceRange: '70,000 - 450,000',
    rating: 4.6,
  },
  {
    id: 4,
    name: 'Kibale National Park',
    slug: 'kibale',
    description: 'Track chimpanzees and explore the primate capital of the world',
    image: 'https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=800&q=80',
    stays: 28,
    priceRange: '50,000 - 350,000',
    rating: 4.8,
  },
  {
    id: 5,
    name: 'Kidepo Valley National Park',
    slug: 'kidepo',
    description: 'Uganda\'s most remote wilderness with authentic African savanna',
    image: 'https://images.unsplash.com/photo-1535338454770-6c4f504d5f6b?w=800&q=80',
    stays: 18,
    priceRange: '40,000 - 300,000',
    rating: 4.9,
  },
  {
    id: 6,
    name: 'Lake Mburo National Park',
    slug: 'lake-mburo',
    description: 'Zebras, impalas, and water buffalo in Uganda\'s biggest game reserve',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    stays: 22,
    priceRange: '55,000 - 320,000',
    rating: 4.5,
  },
]

export const getHostSpotlights = () => [
  {
    id: 1,
    name: 'Auntie Grace Mwesigwa',
    property: 'Grace\'s Forest Homestay',
    location: 'Bwindi Impenetrable',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    quote: 'Hosting gorilla trekkers changed our village. My family now sends children to school and we\'ve expanded our farm. Shakes Travel made it possible.',
    rating: 5,
    reviews: 87,
    womenLed: true,
    ecocertified: true,
    newHost: false,
  },
  {
    id: 2,
    name: 'James Kateregga',
    property: 'Kibale Chimp Lodge',
    location: 'Kibale National Park',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80',
    quote: 'I was just a guide until I partnered with Shakes. Now I run a 6-bedroom lodge. The platform handled payments, marketing – I just focused on hospitality.',
    rating: 5,
    reviews: 124,
    womenLed: false,
    ecocertified: true,
    newHost: false,
  },
  {
    id: 3,
    name: 'Patricia & Rose Nakato',
    property: 'Sisters\' Safari Eco-Camp',
    location: 'Queen Elizabeth National Park',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    quote: 'Two sisters, one vision – sustainable tourism. With Shakes, we went from renting rooms to operating a full eco-camp with 40+ bookings monthly.',
    rating: 4.9,
    reviews: 156,
    womenLed: true,
    ecocertified: true,
    newHost: false,
  },
  {
    id: 4,
    name: 'Moses Ochieng',
    property: 'Murchison Riverside Camp',
    location: 'Murchison Falls',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    quote: 'My father built this lodge decades ago. Shakes helped us go digital and reach international travelers. We\'re now fully booked in high season.',
    rating: 4.8,
    reviews: 98,
    womenLed: false,
    ecocertified: false,
    newHost: false,
  },
  {
    id: 5,
    name: 'Fatima Hassan',
    property: 'Kidepo Nomad Tents',
    location: 'Kidepo Valley',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    quote: 'We brought traditional nomadic hospitality to eco-tourism. Shakes connected us with travelers seeking authentic experiences. Life-changing!',
    rating: 4.9,
    reviews: 67,
    womenLed: true,
    ecocertified: true,
    newHost: true,
  },
]

export const getAllStays = () => [
  // Bwindi stays
  {
    id: 1,
    name: 'Grace\'s Forest Homestay',
    destination: 'bwindi',
    location: 'Bwindi Impenetrable National Park',
    propertyType: 'Homestay',
    image: 'https://images.unsplash.com/photo-1578049635882-6e82b35bac80?w=500&q=80',
    hostName: 'Auntie Grace',
    hostImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=50&q=80',
    pricePerNight: 120000,
    rating: 5,
    reviews: 87,
    description: 'Experience authentic Ugandan hospitality in a cozy home setting. Wake up to the sounds of the rainforest and enjoy home-cooked traditional meals.',
    amenities: ['Hot Water', 'Meals Included', 'Guides Available', 'WiFi'],
    maxGuests: 4,
    bedrooms: 2,
    isFeatured: true,
    ecocertified: true,
    womenLed: true,
    availableUntil: '5 spots',
  },
  {
    id: 2,
    name: 'Misty Gorilla Lodge',
    destination: 'bwindi',
    location: 'Bwindi Impenetrable National Park',
    propertyType: 'Lodge',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&q=80',
    hostName: 'Simon Kato',
    hostImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50&q=80',
    pricePerNight: 280000,
    rating: 4.8,
    reviews: 62,
    description: 'Luxury accommodations with forest views. Professional guides, gourmet dining, and world-class service.',
    amenities: ['WiFi', 'Hot Water', 'Meals Included', 'Swimming Pool', 'Guides Available'],
    maxGuests: 8,
    bedrooms: 4,
    isFeatured: false,
    ecocertified: true,
    womenLed: false,
    availableUntil: '8 spots',
  },
  {
    id: 3,
    name: 'Bwindi Eco-Cabins',
    destination: 'bwindi',
    location: 'Bwindi Impenetrable National Park',
    propertyType: 'Eco-Cabin',
    image: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=500&q=80',
    hostName: 'Eco-Lodges Uganda',
    hostImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=50&q=80',
    pricePerNight: 180000,
    rating: 4.9,
    reviews: 45,
    description: 'Solar-powered eco-cabins built from sustainable materials. Immerse yourself in nature while reducing your carbon footprint.',
    amenities: ['Hot Water', 'Meals Included', 'Guides Available', 'Garden'],
    maxGuests: 6,
    bedrooms: 3,
    isFeatured: true,
    ecocertified: true,
    womenLed: false,
    availableUntil: '3 spots',
  },
  {
    id: 4,
    name: 'Gorilla Haven Tented Camp',
    destination: 'bwindi',
    location: 'Bwindi Impenetrable National Park',
    propertyType: 'Tented Camp',
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0b0c201d?w=500&q=80',
    hostName: 'David Kabugo',
    hostImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=50&q=80',
    pricePerNight: 150000,
    rating: 4.7,
    reviews: 38,
    description: 'Glamping at its finest. Spacious safari tents with en-suite bathrooms overlooking the forest. Perfect for adventure seekers.',
    amenities: ['Hot Water', 'Guides Available', 'WiFi', 'Parking'],
    maxGuests: 5,
    bedrooms: 2,
    isFeatured: false,
    ecocertified: false,
    womenLed: false,
    availableUntil: null,
  },

  // Queen Elizabeth stays
  {
    id: 5,
    name: 'Sisters\' Safari Eco-Camp',
    destination: 'queen-elizabeth',
    location: 'Queen Elizabeth National Park',
    propertyType: 'Eco-Cabin',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=500&q=80',
    hostName: 'Patricia & Rose',
    hostImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=50&q=80',
    pricePerNight: 200000,
    rating: 4.9,
    reviews: 156,
    description: 'Two sisters built this sustainable eco-camp. Experience the best of Uganda\'s hospitality with tree-climbing lion tours and boat safaris.',
    amenities: ['Hot Water', 'Meals Included', 'Guides Available', 'Swimming Pool'],
    maxGuests: 12,
    bedrooms: 6,
    isFeatured: true,
    ecocertified: true,
    womenLed: true,
    availableUntil: '2 spots',
  },
  {
    id: 6,
    name: 'Kazinga Channel Tented Resort',
    destination: 'queen-elizabeth',
    location: 'Queen Elizabeth National Park',
    propertyType: 'Tented Camp',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&q=80',
    hostName: 'Robert Ssemanda',
    hostImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50&q=80',
    pricePerNight: 250000,
    rating: 4.6,
    reviews: 92,
    description: 'Waterfront tents with premium amenities. Direct access to boat safaris and wildlife viewing. All-inclusive packages available.',
    amenities: ['WiFi', 'Hot Water', 'Meals Included', 'Swimming Pool', 'Guides Available'],
    maxGuests: 10,
    bedrooms: 5,
    isFeatured: false,
    ecocertified: true,
    womenLed: false,
    availableUntil: null,
  },
  {
    id: 7,
    name: 'Lion View Homestay',
    destination: 'queen-elizabeth',
    location: 'Queen Elizabeth National Park',
    propertyType: 'Homestay',
    image: 'https://images.unsplash.com/photo-1578049635882-6e82b35bac80?w=500&q=80',
    hostName: 'Margaret Nabwire',
    hostImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=50&q=80',
    pricePerNight: 100000,
    rating: 4.5,
    reviews: 41,
    description: 'Family-run guesthouse with local charm. Homemade breakfast and dinner. Meet locals and learn about Ugandan culture.',
    amenities: ['Hot Water', 'Meals Included', 'Garden', 'Parking'],
    maxGuests: 6,
    bedrooms: 3,
    isFeatured: false,
    ecocertified: false,
    womenLed: true,
    availableUntil: '4 spots',
  },

  // Kibale stays
  {
    id: 8,
    name: 'Kibale Chimp Lodge',
    destination: 'kibale',
    location: 'Kibale National Park',
    propertyType: 'Lodge',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&q=80',
    hostName: 'James Kateregga',
    hostImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50&q=80',
    pricePerNight: 220000,
    rating: 5,
    reviews: 124,
    description: 'Former guide turned lodge owner. Expert insights on chimpanzee behavior. Beautiful grounds with 13 primate-viewing spots.',
    amenities: ['WiFi', 'Hot Water', 'Meals Included', 'Guides Available', 'Parking'],
    maxGuests: 10,
    bedrooms: 5,
    isFeatured: true,
    ecocertified: true,
    womenLed: false,
    availableUntil: null,
  },
  {
    id: 9,
    name: 'Primate Sanctuary Guest House',
    destination: 'kibale',
    location: 'Kibale National Park',
    propertyType: 'Guest House',
    image: 'https://images.unsplash.com/photo-1578049635882-6e82b35bac80?w=500&q=80',
    hostName: 'Dr. Moses Bakuneeta',
    hostImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=50&q=80',
    pricePerNight: 160000,
    rating: 4.8,
    reviews: 55,
    description: 'Researcher-owned guesthouse. Learn about primate conservation while staying. Educational programs available.',
    amenities: ['Hot Water', 'Meals Included', 'Guides Available', 'WiFi'],
    maxGuests: 8,
    bedrooms: 4,
    isFeatured: false,
    ecocertified: true,
    womenLed: false,
    availableUntil: '2 spots',
  },

  // Murchison Falls stays
  {
    id: 10,
    name: 'Murchison Riverside Camp',
    destination: 'murchison',
    location: 'Murchison Falls National Park',
    propertyType: 'Tented Camp',
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0b0c201d?w=500&q=80',
    hostName: 'Moses Ochieng',
    hostImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=50&q=80',
    pricePerNight: 280000,
    rating: 4.8,
    reviews: 98,
    description: 'Historic lodge on the Nile. Witness the Murchison Falls explosion. Nile river safaris and game drives included.',
    amenities: ['WiFi', 'Hot Water', 'Meals Included', 'Swimming Pool', 'Guides Available'],
    maxGuests: 12,
    bedrooms: 6,
    isFeatured: true,
    ecocertified: false,
    womenLed: false,
    availableUntil: null,
  },
  {
    id: 11,
    name: 'Nile Falls Lodge',
    destination: 'murchison',
    location: 'Murchison Falls National Park',
    propertyType: 'Lodge',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&q=80',
    hostName: 'Henry Kiggundu',
    hostImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50&q=80',
    pricePerNight: 320000,
    rating: 4.7,
    reviews: 76,
    description: 'Luxury lodge with panoramic falls views. Premium dining, spa services, and curated safari experiences.',
    amenities: ['WiFi', 'Hot Water', 'Meals Included', 'Swimming Pool', 'Guides Available', 'Parking'],
    maxGuests: 14,
    bedrooms: 7,
    isFeatured: false,
    ecocertified: true,
    womenLed: false,
    availableUntil: '1 spot',
  },

  // Kidepo Valley stays
  {
    id: 12,
    name: 'Kidepo Nomad Tents',
    destination: 'kidepo',
    location: 'Kidepo Valley National Park',
    propertyType: 'Tented Camp',
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0b0c201d?w=500&q=80',
    hostName: 'Fatima Hassan',
    hostImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=50&q=80',
    pricePerNight: 180000,
    rating: 4.9,
    reviews: 67,
    description: 'Traditional nomadic hospitality meets modern comfort. Authentic Karamojong cultural experiences. Remote wilderness adventure.',
    amenities: ['Hot Water', 'Meals Included', 'Guides Available', 'Garden'],
    maxGuests: 8,
    bedrooms: 4,
    isFeatured: true,
    ecocertified: true,
    womenLed: true,
    availableUntil: '6 spots',
  },
  {
    id: 13,
    name: 'Apoka Safari Lodge',
    destination: 'kidepo',
    location: 'Kidepo Valley National Park',
    propertyType: 'Lodge',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&q=80',
    hostName: 'Paul Akol',
    hostImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=50&q=80',
    pricePerNight: 240000,
    rating: 4.9,
    reviews: 52,
    description: 'The only lodge in Kidepo. Exceptional wildlife encounters and cultural tourism. Expert guides and naturalists.',
    amenities: ['WiFi', 'Hot Water', 'Meals Included', 'Swimming Pool', 'Guides Available'],
    maxGuests: 10,
    bedrooms: 5,
    isFeatured: false,
    ecocertified: true,
    womenLed: false,
    availableUntil: null,
  },

  // Lake Mburo stays
  {
    id: 14,
    name: 'Mburo Lakeside Eco-Resort',
    destination: 'lake-mburo',
    location: 'Lake Mburo National Park',
    propertyType: 'Resort',
    image: 'https://images.unsplash.com/photo-1546899402-a5dbe6d01220?w=500&q=80',
    hostName: 'Stella Mwesigire',
    hostImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=50&q=80',
    pricePerNight: 200000,
    rating: 4.8,
    reviews: 89,
    description: 'Waterfront eco-resort with zebra and antelope herds. Boat safaris, horseback riding, and fishing available.',
    amenities: ['WiFi', 'Hot Water', 'Meals Included', 'Swimming Pool', 'Guides Available', 'Parking'],
    maxGuests: 12,
    bedrooms: 6,
    isFeatured: true,
    ecocertified: true,
    womenLed: true,
    availableUntil: '3 spots',
  },
  {
    id: 15,
    name: 'Zebra Plains Lodge',
    destination: 'lake-mburo',
    location: 'Lake Mburo National Park',
    propertyType: 'Lodge',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&q=80',
    hostName: 'William Tumusiime',
    hostImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50&q=80',
    pricePerNight: 220000,
    rating: 4.7,
    reviews: 71,
    description: 'Game viewing lodge with professional naturalists. Wildlife photography packages and seasonal migration tours.',
    amenities: ['WiFi', 'Hot Water', 'Meals Included', 'Guides Available', 'Parking'],
    maxGuests: 10,
    bedrooms: 5,
    isFeatured: false,
    ecocertified: true,
    womenLed: false,
    availableUntil: null,
  },
]
